services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    command: [ "postgres", "-c", "log_statement=all" ] # log all queries into the container log file
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./local/postgres/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
