// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: orbital/task_request.proto

package orbital

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskRequest is the request object that will be sent to the operator.
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,10,opt,name=taskId,proto3" json:"taskId,omitempty"`             // UUID as string
	Type          string                 `protobuf:"bytes,20,opt,name=type,proto3" json:"type,omitempty"`                 // Type of the task
	Data          []byte                 `protobuf:"bytes,30,opt,name=data,proto3,oneof" json:"data,omitempty"`           // Static context for the task
	WorkingState  []byte                 `protobuf:"bytes,40,opt,name=workingState,proto3" json:"workingState,omitempty"` // Current state of the task
	Etag          string                 `protobuf:"bytes,50,opt,name=etag,proto3" json:"etag,omitempty"`                 // Versioning tag
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_orbital_task_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbital_task_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_orbital_task_request_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TaskRequest) GetWorkingState() []byte {
	if x != nil {
		return x.WorkingState
	}
	return nil
}

func (x *TaskRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

var File_orbital_task_request_proto protoreflect.FileDescriptor

const file_orbital_task_request_proto_rawDesc = "" +
	"\n" +
	"\x1aorbital/task_request.proto\x12\aorbital\"\x93\x01\n" +
	"\vTaskRequest\x12\x16\n" +
	"\x06taskId\x18\n" +
	" \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x14 \x01(\tR\x04type\x12\x17\n" +
	"\x04data\x18\x1e \x01(\fH\x00R\x04data\x88\x01\x01\x12\"\n" +
	"\fworkingState\x18( \x01(\fR\fworkingState\x12\x12\n" +
	"\x04etag\x182 \x01(\tR\x04etagB\a\n" +
	"\x05_datab\x06proto3"

var (
	file_orbital_task_request_proto_rawDescOnce sync.Once
	file_orbital_task_request_proto_rawDescData []byte
)

func file_orbital_task_request_proto_rawDescGZIP() []byte {
	file_orbital_task_request_proto_rawDescOnce.Do(func() {
		file_orbital_task_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orbital_task_request_proto_rawDesc), len(file_orbital_task_request_proto_rawDesc)))
	})
	return file_orbital_task_request_proto_rawDescData
}

var file_orbital_task_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_orbital_task_request_proto_goTypes = []any{
	(*TaskRequest)(nil), // 0: orbital.TaskRequest
}
var file_orbital_task_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orbital_task_request_proto_init() }
func file_orbital_task_request_proto_init() {
	if File_orbital_task_request_proto != nil {
		return
	}
	file_orbital_task_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orbital_task_request_proto_rawDesc), len(file_orbital_task_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orbital_task_request_proto_goTypes,
		DependencyIndexes: file_orbital_task_request_proto_depIdxs,
		MessageInfos:      file_orbital_task_request_proto_msgTypes,
	}.Build()
	File_orbital_task_request_proto = out.File
	file_orbital_task_request_proto_goTypes = nil
	file_orbital_task_request_proto_depIdxs = nil
}
