{
 "title": "Manager Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "description": "What to watch for: Ratios below 0.99 (99%) might indicate you need more memory for your workload.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum(heap_blks_read) as heap_read,\n  sum(heap_blks_hit) as heap_hit,\n  sum(heap_blks_hit) / (sum(heap_blks_hit) + sum(heap_blks_read)) as ratio\nFROM pg_statio_user_tables;"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "bargauge",
   "description": "19\n\n\nAggregation of all postgres sessions per their status ",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "select state, count(*) from pg_stat_activity  where pid <> pg_backend_pid() group by 1 order by 1;"
    }
   ]
  },
  {
   "title": "current connection state",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  datname, \n  usename, \n  application_name,\n  state, \n  count(*),\n  max(extract(epoch from now() - state_change)) as max_state_duration_sec\nFROM pg_stat_activity \nWHERE state IS NOT NULL\nGROUP BY 1, 2, 3, 4\nORDER BY count(*) DESC;"
    }
   ]
  },
  {
   "title": "JOB Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"TOTAL\",\n  COUNT(CASE WHEN status = 'CREATED' THEN 1 END) AS \"CREATED\",\n  COUNT(CASE WHEN status = 'CONFIRMED' THEN 1 END) AS \"CONFIRMED\",\n  COUNT(CASE WHEN status = 'RESOLVING' THEN 1 END) AS \"RESOLVING\",\n  COUNT(CASE WHEN status = 'READY' THEN 1 END) AS \"READY\",\n  COUNT(CASE WHEN status = 'PROCESSING' THEN 1 END) AS \"PROCESSING\",\n  COUNT(CASE WHEN status = 'DONE' THEN 1 END) AS \"DONE\",\n  COUNT(CASE WHEN status = 'FAILED' THEN 1 END) AS \"FAILED\",\n  COUNT(CASE WHEN status = 'RESOLVE_CANCELED' THEN 1 END) AS \"RESOLVE_CANCELED\",\n  COUNT(CASE WHEN status = 'CONFIRM_CANCELED' THEN 1 END) AS \"CONFIRM_CANCELED\",\n  COUNT(CASE WHEN status = 'USER_CANCELED' THEN 1 END) AS \"USER_CANCELED\"\nFROM jobs;"
    }
   ]
  },
  {
   "title": "Task",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"TOTAL\",\n  COUNT(CASE WHEN status = 'CREATED' THEN 1 END) AS \"CREATED\",\n  COUNT(CASE WHEN status = 'PROCESSING' THEN 1 END) AS \"PROCESSING\",\n  COUNT(CASE WHEN status = 'DONE' THEN 1 END) AS \"DONE\",\n   COUNT(CASE WHEN status = 'FAILED' THEN 1 END) AS \"FAILED\"\nFROM tasks;\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Job Event",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"TOTAL\",\n  COUNT(CASE WHEN is_notified = true THEN 1 END) AS \"SEND\",\n  COUNT(CASE WHEN is_notified = false THEN 1 END) AS \"NOT_SEND\"\nFROM job_event;"
    }
   ]
  },
  {
   "title": "long-running transactions ",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \n  pid, \n  usename, \n  application_name,\n  state,\n  age(now(), xact_start) as xact_age,\n  wait_event_type,\n  wait_event,\n  query\nFROM pg_stat_activity \nWHERE xact_start IS NOT NULL\nORDER BY xact_start ASC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "go_threads",
   "type": "timeseries",
   "description": "The number of OS threads created. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    { "expr": "go_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "timeseries",
   "description": "A gauge that represents the number of goroutines that are currently active. High goroutine counts can indicate potential performance bottlenecks. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_heap_inuse_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes that are currently in use. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_heap_sys_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes obtained from the system. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    { "expr": "go_memstats_heap_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_heap_alloc_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes allocated and still in use. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes",
   "type": "timeseries",
   "description": "Number of bytes allocated and still in use. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_gc_duration_seconds",
   "type": "histogram",
   "description": "A histogram that tracks the duration of garbage collection cycles. Useful for understanding how frequently and for how long the garbage collector is running. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_heap_released_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes released back to the OS. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "go_memstats_heap_released_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_heap_idle_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes that are idle and available for allocation. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    { "expr": "go_memstats_heap_idle_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_mallocs_total",
   "type": "timeseries",
   "description": "Number of mallocs. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    { "expr": "go_memstats_mallocs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go_memstats_frees_total",
   "type": "timeseries",
   "description": "Number of frees. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    { "expr": "go_memstats_frees_total", "legendFormat": "__auto" }
   ]
  }
 ]
}