// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: orbital/v1/task_response.proto

package orbitalv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TaskResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TaskResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TaskResponseMultiError, or
// nil if none found.
func (m *TaskResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	// no validation rules for Type

	// no validation rules for ExternalId

	// no validation rules for Etag

	// no validation rules for Status

	// no validation rules for ReconcileAfterSec

	// no validation rules for MetaData

	if m.WorkingState != nil {
		// no validation rules for WorkingState
	}

	if m.ErrorMessage != nil {
		// no validation rules for ErrorMessage
	}

	if len(errors) > 0 {
		return TaskResponseMultiError(errors)
	}

	return nil
}

// TaskResponseMultiError is an error wrapping multiple validation errors
// returned by TaskResponse.ValidateAll() if the designated constraints aren't met.
type TaskResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskResponseMultiError) AllErrors() []error { return m }

// TaskResponseValidationError is the validation error returned by
// TaskResponse.Validate if the designated constraints aren't met.
type TaskResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskResponseValidationError) ErrorName() string { return "TaskResponseValidationError" }

// Error satisfies the builtin error interface
func (e TaskResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskResponseValidationError{}
