// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: orbital/v1/task_response.proto

package orbitalv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskStatus defines the possible statuses of a task.
type TaskStatus int32

const (
	TaskStatus_PROCESSING TaskStatus = 0 // operator is still working on the task
	TaskStatus_DONE       TaskStatus = 1 // operator has completed the task
	TaskStatus_FAILED     TaskStatus = 2 // operator encountered an error
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "PROCESSING",
		1: "DONE",
		2: "FAILED",
	}
	TaskStatus_value = map[string]int32{
		"PROCESSING": 0,
		"DONE":       1,
		"FAILED":     2,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orbital_v1_task_response_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_orbital_v1_task_response_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_orbital_v1_task_response_proto_rawDescGZIP(), []int{0}
}

// TaskResponse is the response object received from the operator.
type TaskResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,10,opt,name=taskId,proto3" json:"taskId,omitempty"`                             // UUID as string
	Type              string                 `protobuf:"bytes,20,opt,name=type,proto3" json:"type,omitempty"`                                 // Type of the task
	ExternalId        string                 `protobuf:"bytes,25,opt,name=externalId,proto3" json:"externalId,omitempty"`                     // External ID serves as an identifier for a Job.
	WorkingState      []byte                 `protobuf:"bytes,30,opt,name=workingState,proto3,oneof" json:"workingState,omitempty"`           // Updated state of the task
	Etag              string                 `protobuf:"bytes,40,opt,name=etag,proto3" json:"etag,omitempty"`                                 // Correlates with TaskRequest
	Status            TaskStatus             `protobuf:"varint,50,opt,name=status,proto3,enum=orbital.v1.TaskStatus" json:"status,omitempty"` // Status of the task
	ErrorMessage      *string                `protobuf:"bytes,60,opt,name=errorMessage,proto3,oneof" json:"errorMessage,omitempty"`           // Optional error message
	ReconcileAfterSec int64                  `protobuf:"varint,70,opt,name=reconcileAfterSec,proto3" json:"reconcileAfterSec,omitempty"`      // Time in seconds to delay next retry
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_orbital_v1_task_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orbital_v1_task_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_orbital_v1_task_response_proto_rawDescGZIP(), []int{0}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskResponse) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *TaskResponse) GetWorkingState() []byte {
	if x != nil {
		return x.WorkingState
	}
	return nil
}

func (x *TaskResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *TaskResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_PROCESSING
}

func (x *TaskResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *TaskResponse) GetReconcileAfterSec() int64 {
	if x != nil {
		return x.ReconcileAfterSec
	}
	return 0
}

var File_orbital_v1_task_response_proto protoreflect.FileDescriptor

const file_orbital_v1_task_response_proto_rawDesc = "" +
	"\n" +
	"\x1eorbital/v1/task_response.proto\x12\n" +
	"orbital.v1\"\xc0\x02\n" +
	"\fTaskResponse\x12\x16\n" +
	"\x06taskId\x18\n" +
	" \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x14 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"externalId\x18\x19 \x01(\tR\n" +
	"externalId\x12'\n" +
	"\fworkingState\x18\x1e \x01(\fH\x00R\fworkingState\x88\x01\x01\x12\x12\n" +
	"\x04etag\x18( \x01(\tR\x04etag\x12.\n" +
	"\x06status\x182 \x01(\x0e2\x16.orbital.v1.TaskStatusR\x06status\x12'\n" +
	"\ferrorMessage\x18< \x01(\tH\x01R\ferrorMessage\x88\x01\x01\x12,\n" +
	"\x11reconcileAfterSec\x18F \x01(\x03R\x11reconcileAfterSecB\x0f\n" +
	"\r_workingStateB\x0f\n" +
	"\r_errorMessage*2\n" +
	"\n" +
	"TaskStatus\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x00\x12\b\n" +
	"\x04DONE\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02B\xa3\x01\n" +
	"\x0ecom.orbital.v1B\x11TaskResponseProtoP\x01Z5github.com/openkcm/orbital/proto/orbital/v1;orbitalv1\xa2\x02\x03OXX\xaa\x02\n" +
	"Orbital.V1\xca\x02\n" +
	"Orbital\\V1\xe2\x02\x16Orbital\\V1\\GPBMetadata\xea\x02\vOrbital::V1b\x06proto3"

var (
	file_orbital_v1_task_response_proto_rawDescOnce sync.Once
	file_orbital_v1_task_response_proto_rawDescData []byte
)

func file_orbital_v1_task_response_proto_rawDescGZIP() []byte {
	file_orbital_v1_task_response_proto_rawDescOnce.Do(func() {
		file_orbital_v1_task_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orbital_v1_task_response_proto_rawDesc), len(file_orbital_v1_task_response_proto_rawDesc)))
	})
	return file_orbital_v1_task_response_proto_rawDescData
}

var file_orbital_v1_task_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orbital_v1_task_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_orbital_v1_task_response_proto_goTypes = []any{
	(TaskStatus)(0),      // 0: orbital.v1.TaskStatus
	(*TaskResponse)(nil), // 1: orbital.v1.TaskResponse
}
var file_orbital_v1_task_response_proto_depIdxs = []int32{
	0, // 0: orbital.v1.TaskResponse.status:type_name -> orbital.v1.TaskStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orbital_v1_task_response_proto_init() }
func file_orbital_v1_task_response_proto_init() {
	if File_orbital_v1_task_response_proto != nil {
		return
	}
	file_orbital_v1_task_response_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orbital_v1_task_response_proto_rawDesc), len(file_orbital_v1_task_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orbital_v1_task_response_proto_goTypes,
		DependencyIndexes: file_orbital_v1_task_response_proto_depIdxs,
		EnumInfos:         file_orbital_v1_task_response_proto_enumTypes,
		MessageInfos:      file_orbital_v1_task_response_proto_msgTypes,
	}.Build()
	File_orbital_v1_task_response_proto = out.File
	file_orbital_v1_task_response_proto_goTypes = nil
	file_orbital_v1_task_response_proto_depIdxs = nil
}
