// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: orbital/v1/task_request.proto

package orbitalv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TaskRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TaskRequestMultiError, or
// nil if none found.
func (m *TaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	// no validation rules for Type

	// no validation rules for ExternalId

	// no validation rules for WorkingState

	// no validation rules for Etag

	// no validation rules for MetaData

	if m.Data != nil {
		// no validation rules for Data
	}

	if len(errors) > 0 {
		return TaskRequestMultiError(errors)
	}

	return nil
}

// TaskRequestMultiError is an error wrapping multiple validation errors
// returned by TaskRequest.ValidateAll() if the designated constraints aren't met.
type TaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskRequestMultiError) AllErrors() []error { return m }

// TaskRequestValidationError is the validation error returned by
// TaskRequest.Validate if the designated constraints aren't met.
type TaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskRequestValidationError) ErrorName() string { return "TaskRequestValidationError" }

// Error satisfies the builtin error interface
func (e TaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskRequestValidationError{}
