// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orbital/v1/task_request.proto

package orbitalv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskRequest is the request object that will be sent to the operator.
type TaskRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskId               string                 `protobuf:"bytes,10,opt,name=taskId,proto3" json:"taskId,omitempty"`                                                                               // UUID as string
	Type                 string                 `protobuf:"bytes,20,opt,name=type,proto3" json:"type,omitempty"`                                                                                   // Type of the task
	ExternalId           string                 `protobuf:"bytes,25,opt,name=externalId,proto3" json:"externalId,omitempty"`                                                                       // External ID serves as an identifier for a Job.
	Data                 []byte                 `protobuf:"bytes,30,opt,name=data,proto3,oneof" json:"data,omitempty"`                                                                             // Static context for the task
	WorkingState         []byte                 `protobuf:"bytes,40,opt,name=workingState,proto3" json:"workingState,omitempty"`                                                                   // Current state of the task
	Etag                 string                 `protobuf:"bytes,50,opt,name=etag,proto3" json:"etag,omitempty"`                                                                                   // Versioning tag
	MetaData             map[string]string      `protobuf:"bytes,60,rep,name=metaData,proto3" json:"metaData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // MetaData contains additional information about the message
	TaskCreatedAt        int64                  `protobuf:"varint,70,opt,name=taskCreatedAt,proto3" json:"taskCreatedAt,omitempty"`                                                                // Unix timestamp in nanoseconds of when the task was created
	TaskLastReconciledAt int64                  `protobuf:"varint,80,opt,name=taskLastReconciledAt,proto3" json:"taskLastReconciledAt,omitempty"`                                                  // Unix timestamp in nanoseconds of when the task was last reconciled
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_orbital_v1_task_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orbital_v1_task_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_orbital_v1_task_request_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *TaskRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TaskRequest) GetWorkingState() []byte {
	if x != nil {
		return x.WorkingState
	}
	return nil
}

func (x *TaskRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *TaskRequest) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *TaskRequest) GetTaskCreatedAt() int64 {
	if x != nil {
		return x.TaskCreatedAt
	}
	return 0
}

func (x *TaskRequest) GetTaskLastReconciledAt() int64 {
	if x != nil {
		return x.TaskLastReconciledAt
	}
	return 0
}

var File_orbital_v1_task_request_proto protoreflect.FileDescriptor

const file_orbital_v1_task_request_proto_rawDesc = "" +
	"\n" +
	"\x1dorbital/v1/task_request.proto\x12\n" +
	"orbital.v1\"\x8d\x03\n" +
	"\vTaskRequest\x12\x16\n" +
	"\x06taskId\x18\n" +
	" \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x14 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"externalId\x18\x19 \x01(\tR\n" +
	"externalId\x12\x17\n" +
	"\x04data\x18\x1e \x01(\fH\x00R\x04data\x88\x01\x01\x12\"\n" +
	"\fworkingState\x18( \x01(\fR\fworkingState\x12\x12\n" +
	"\x04etag\x182 \x01(\tR\x04etag\x12A\n" +
	"\bmetaData\x18< \x03(\v2%.orbital.v1.TaskRequest.MetaDataEntryR\bmetaData\x12$\n" +
	"\rtaskCreatedAt\x18F \x01(\x03R\rtaskCreatedAt\x122\n" +
	"\x14taskLastReconciledAt\x18P \x01(\x03R\x14taskLastReconciledAt\x1a;\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_dataB\xa2\x01\n" +
	"\x0ecom.orbital.v1B\x10TaskRequestProtoP\x01Z5github.com/openkcm/orbital/proto/orbital/v1;orbitalv1\xa2\x02\x03OXX\xaa\x02\n" +
	"Orbital.V1\xca\x02\n" +
	"Orbital\\V1\xe2\x02\x16Orbital\\V1\\GPBMetadata\xea\x02\vOrbital::V1b\x06proto3"

var (
	file_orbital_v1_task_request_proto_rawDescOnce sync.Once
	file_orbital_v1_task_request_proto_rawDescData []byte
)

func file_orbital_v1_task_request_proto_rawDescGZIP() []byte {
	file_orbital_v1_task_request_proto_rawDescOnce.Do(func() {
		file_orbital_v1_task_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orbital_v1_task_request_proto_rawDesc), len(file_orbital_v1_task_request_proto_rawDesc)))
	})
	return file_orbital_v1_task_request_proto_rawDescData
}

var file_orbital_v1_task_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orbital_v1_task_request_proto_goTypes = []any{
	(*TaskRequest)(nil), // 0: orbital.v1.TaskRequest
	nil,                 // 1: orbital.v1.TaskRequest.MetaDataEntry
}
var file_orbital_v1_task_request_proto_depIdxs = []int32{
	1, // 0: orbital.v1.TaskRequest.metaData:type_name -> orbital.v1.TaskRequest.MetaDataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orbital_v1_task_request_proto_init() }
func file_orbital_v1_task_request_proto_init() {
	if File_orbital_v1_task_request_proto != nil {
		return
	}
	file_orbital_v1_task_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orbital_v1_task_request_proto_rawDesc), len(file_orbital_v1_task_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orbital_v1_task_request_proto_goTypes,
		DependencyIndexes: file_orbital_v1_task_request_proto_depIdxs,
		MessageInfos:      file_orbital_v1_task_request_proto_msgTypes,
	}.Build()
	File_orbital_v1_task_request_proto = out.File
	file_orbital_v1_task_request_proto_goTypes = nil
	file_orbital_v1_task_request_proto_depIdxs = nil
}
