// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orbital/v1/task_service.proto

package orbitalv1

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_orbital_v1_task_service_proto protoreflect.FileDescriptor

const file_orbital_v1_task_service_proto_rawDesc = "" +
	"\n" +
	"\x1dorbital/v1/task_service.proto\x12\n" +
	"orbital.v1\x1a\x1dorbital/v1/task_request.proto\x1a\x1eorbital/v1/task_response.proto2S\n" +
	"\vTaskService\x12D\n" +
	"\x0fSendTaskRequest\x12\x17.orbital.v1.TaskRequest\x1a\x18.orbital.v1.TaskResponseB\xa2\x01\n" +
	"\x0ecom.orbital.v1B\x10TaskServiceProtoP\x01Z5github.com/openkcm/orbital/proto/orbital/v1;orbitalv1\xa2\x02\x03OXX\xaa\x02\n" +
	"Orbital.V1\xca\x02\n" +
	"Orbital\\V1\xe2\x02\x16Orbital\\V1\\GPBMetadata\xea\x02\vOrbital::V1b\x06proto3"

var file_orbital_v1_task_service_proto_goTypes = []any{
	(*TaskRequest)(nil),  // 0: orbital.v1.TaskRequest
	(*TaskResponse)(nil), // 1: orbital.v1.TaskResponse
}
var file_orbital_v1_task_service_proto_depIdxs = []int32{
	0, // 0: orbital.v1.TaskService.SendTaskRequest:input_type -> orbital.v1.TaskRequest
	1, // 1: orbital.v1.TaskService.SendTaskRequest:output_type -> orbital.v1.TaskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orbital_v1_task_service_proto_init() }
func file_orbital_v1_task_service_proto_init() {
	if File_orbital_v1_task_service_proto != nil {
		return
	}
	file_orbital_v1_task_request_proto_init()
	file_orbital_v1_task_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orbital_v1_task_service_proto_rawDesc), len(file_orbital_v1_task_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orbital_v1_task_service_proto_goTypes,
		DependencyIndexes: file_orbital_v1_task_service_proto_depIdxs,
	}.Build()
	File_orbital_v1_task_service_proto = out.File
	file_orbital_v1_task_service_proto_goTypes = nil
	file_orbital_v1_task_service_proto_depIdxs = nil
}
