{
 "title": "Go Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "go_threads",
   "type": "timeseries",
   "description": "The number of OS threads created. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_threads{instance=\"manager-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "timeseries",
   "description": "A gauge that represents the number of goroutines that are currently active. High goroutine counts can indicate potential performance bottlenecks. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"manager-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_heap_inuse_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes that are currently in use. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"manager-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_heap_sys_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes obtained from the system. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"manager-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_heap_alloc_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes allocated and still in use. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"manager-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes",
   "type": "timeseries",
   "description": "Number of bytes allocated and still in use. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"manager-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"manager-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_gc_duration_seconds",
   "type": "histogram",
   "description": "A histogram that tracks the duration of garbage collection cycles. Useful for understanding how frequently and for how long the garbage collector is running. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=\"manager-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_heap_released_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes released back to the OS. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "go_memstats_heap_released_bytes{instance=\"manager-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_heap_idle_bytes",
   "type": "timeseries",
   "description": "Number of heap bytes that are idle and available for allocation. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "go_memstats_heap_idle_bytes{instance=\"manager-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_mallocs_total",
   "type": "timeseries",
   "description": "Number of mallocs. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=\"manager-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go_memstats_frees_total",
   "type": "timeseries",
   "description": "Number of frees. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "go_memstats_frees_total{instance=\"manager-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}