{
 "title": "Orbital Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "JOB Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"TOTAL\",\n  COUNT(CASE WHEN status = 'CREATED' THEN 1 END) AS \"CREATED\",\n  COUNT(CASE WHEN status = 'CONFIRMED' THEN 1 END) AS \"CONFIRMED\",\n  COUNT(CASE WHEN status = 'RESOLVING' THEN 1 END) AS \"RESOLVING\",\n  COUNT(CASE WHEN status = 'READY' THEN 1 END) AS \"READY\",\n  COUNT(CASE WHEN status = 'PROCESSING' THEN 1 END) AS \"PROCESSING\",\n  COUNT(CASE WHEN status = 'DONE' THEN 1 END) AS \"DONE\",\n  COUNT(CASE WHEN status = 'FAILED' THEN 1 END) AS \"FAILED\",\n  COUNT(CASE WHEN status = 'RESOLVE_CANCELED' THEN 1 END) AS \"RESOLVE_CANCELED\",\n  COUNT(CASE WHEN status = 'CONFIRM_CANCELED' THEN 1 END) AS \"CONFIRM_CANCELED\",\n  COUNT(CASE WHEN status = 'USER_CANCELED' THEN 1 END) AS \"USER_CANCELED\"\nFROM jobs;"
    }
   ]
  },
  {
   "title": "Task",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"TOTAL\",\n  COUNT(CASE WHEN status = 'CREATED' THEN 1 END) AS \"CREATED\",\n  COUNT(CASE WHEN status = 'PROCESSING' THEN 1 END) AS \"PROCESSING\",\n  COUNT(CASE WHEN status = 'DONE' THEN 1 END) AS \"DONE\",\n   COUNT(CASE WHEN status = 'FAILED' THEN 1 END) AS \"FAILED\"\nFROM tasks;\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Job Event",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"TOTAL\",\n  COUNT(CASE WHEN is_notified = true THEN 1 END) AS \"SEND\",\n  COUNT(CASE WHEN is_notified = false THEN 1 END) AS \"NOT_SEND\"\nFROM job_event;"
    }
   ]
  }
 ]
}