name: Git
permissions:
  contents: read

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  release:
    uses: openkcm/build/.github/workflows/release.lib.yaml@main
    secrets: inherit
